# Generated by Django 5.1.1 on 2024-09-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
    ]
