# Generated by Django 5.1.1 on 2024-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0003_rename_production_production_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
