# Generated by Django 5.1.1 on 2024-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='returns',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ItemReturn',
        ),
    ]
