# Generated by Django 5.1.1 on 2024-09-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0005_item_returns_delete_itemreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='state',
            field=models.CharField(choices=[('p', 'paid'), ('r', 'remain'), ('u', 'unpaid')], default='u', max_length=1),
        ),
    ]
