# Generated by Django 5.1.1 on 2024-09-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0006_alter_command_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='returns',
        ),
    ]
