# Generated by Django 5.1.1 on 2024-09-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0011_payment_method_payment_status_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PAID', 'paid'), ('REMAIN', 'remain'), ('UNPAID', 'unpaid')], default='UNPAID', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mill.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='mill.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='mill.order'),
        ),
        migrations.DeleteModel(
            name='Command',
        ),
    ]
