# Generated by Django 5.1.1 on 2024-09-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0015_cart_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='mill.customer'),
            preserve_default=False,
        ),
    ]
