# Generated by Django 5.1.1 on 2024-09-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0016_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
    ]
