ORDER_STATUS_PAID = 'PAID'
ORDER_STATUS_REMAIN = 'REMAIN'
ORDER_STATUS_UNPAID = 'UNPAID'
ORDER_STATUS_CHOICES = [
    (ORDER_STATUS_PAID, 'paid'),
    (ORDER_STATUS_REMAIN, 'remain'),
    (ORDER_STATUS_UNPAID, 'unpaid')
]

PAYMENT_STATUS_PENDING = 'PENDING'
PAYMENT_STATUS_COMPLETED = 'COMPLETED'
PAYMENT_STATUS_FAILED = 'FAILED'

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_PENDING, 'pending'),
    (PAYMENT_STATUS_COMPLETED, 'completed'),
    (PAYMENT_STATUS_FAILED, 'failed'),
]


PAYMENT_METHOD_CASH = 'CASH'
PAYMENT_METHOD_CREDIT_CARD = 'CREDIT_CARD'
PAYMENT_METHOD_BANK_TRANSFER = 'BANK_TRANSFER'

PAYMENT_METHOD_CHOICES = [
    (PAYMENT_METHOD_CASH, 'cash'),
    (PAYMENT_METHOD_CREDIT_CARD, 'credit Card'),
    (PAYMENT_METHOD_BANK_TRANSFER, 'bank Transfer'),
]
